In [1]:
! pip install pandas

Requirement already satisfied: pandas in /Users/szelenka/anaconda3/envs/python37/lib/python3.7/site-packages (0.23.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/szelenka/anaconda3/envs/python37/lib/python3.7/site-packages (from pandas) (2.7.5)
Requirement already satisfied: pytz>=2011k in /Users/szelenka/anaconda3/envs/python37/lib/python3.7/site-packages (from pandas) (2018.9)
Requirement already satisfied: numpy>=1.9.0 in /Users/szelenka/anaconda3/envs/python37/lib/python3.7/site-packages (from pandas) (1.15.4)
Requirement already satisfied: six>=1.5 in /Users/szelenka/anaconda3/envs/python37/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)
You are using pip version 19.0, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [1]:
import os
import pandas as pd
%matplotlib inline

In [10]:
df = pd.DataFrame()

for file in filter(lambda x: x.endswith('.csv'), os.listdir('.')):
    try:
        load, api, db, result = file.split('-')
    except ValueError:
        continue
    print(file)
    _df = pd.read_csv(file)
    _df['cpu_load'] = load[:-1]
    _df['cpu_api'] = api[:-1]
    _df['cpu_db'] = db[:-1]
    df = pd.concat([df, _df])

150m-150m-150m-results.csv
100m-150m-200m-results.csv
100m-100m-100m-results.csv
50m-300m-100m-results.csv
50m-100m-300m-results.csv
50m-350m-50m-results.csv
50m-50m-350m-results.csv
25m-400m-25m-results.csv

In [36]:
df['errors'] = df['summary.errors.connect'] + df['summary.errors.read'] + df['summary.errors.write'] + df['summary.errors.status'] + df['summary.errors.timeout']
df['rps'] = (df['summary.requests']) / df['summary.duration']
columns = [
    'cpu_load', 'cpu_api', 'cpu_db', 'title', 'endpoint', 'latency:percentile(90)', 
    'summary.requests', 'errors', 'rps'
]
df = df[columns]

In [40]:
def plot(endpoint = '/remote'):
    t = df[(df.endpoint == endpoint)]
    return t[t['cpu_load'] == '50']

plot()

,cpu_load,cpu_api,cpu_db,title,endpoint,latency:percentile(90),summary.requests,errors,rps
1,50,300,100,falcon,/remote,4004.29,4299,648,71.590341
4,50,300,100,flask,/remote,4614.42,4330,693,72.070573
7,50,300,100,sanic,/remote,1101.27,8043,15,133.849226
10,50,300,100,starlette,/remote,1195.53,7814,31,130.059920
1,50,100,300,falcon,/remote,4796.05,1698,1002,28.262317
4,50,100,300,flask,/remote,4600.81,1532,896,25.499334
7,50,100,300,sanic,/remote,3401.53,4663,0,77.600266
10,50,100,300,starlette,/remote,4396.72,3986,324,66.355918
1,50,350,50,falcon,/remote,4295.98,4385,732,72.961730
4,50,350,50,flask,/remote,4262.51,4402,715,73.268975
7,50,350,50,sanic,/remote,1101.83,8094,25,134.720373
10,50,350,50,starlette,/remote,1102.61,8097,29,134.792742
1,50,50,350,falcon,/remote,6096.70,761,695,12.664337
4,50,50,350,flask,/remote,6799.33,638,626,10.619174
7,50,50,350,sanic,/remote,9401.04,1960,125,32.623169
10,50,50,350,starlette,/remote,8802.70,988,932,16.458437